pipeline

diff --git a/.github/workflows/db-migration.yml b/.github/workflows/db-migration.yml
--- a/.github/workflows/db-migration.yml
+++ b/.github/workflows/db-migration.yml
@@ -27,3 +27,48 @@ jobs:
           aws s3 cp init.sql s3://594474085977-devops-scripts/init.sql 
           aws s3 cp init.py s3://594474085977-devops-scripts/init.py 
           echo "✅ Files Uploaded to bucket.."
+
+      - name: Initializing Database on RDS using EC2 
+        id: init
+        run: |
+          CMD_ID=$(aws ssm send-command \
+          --targets "Key=tag:App,Values=flask" \
+          --document-name "AWS-RunShellScript" \
+          --parameters '{"commands":[
+          "aws s3 cp s3://594474085977-devops-script/init.py /tmp/init.py",
+          "aws s3 cp s3://594474085977-devops-script/init.sql /tmp/init.sql",
+          "python3 /tmp/init.py",
+          "rm -f /tmp/init.py /tmp/init.sql"
+          ]}' \
+          --query 'Command.CommandId' \
+          --output text \
+          --region us-west-1)
+
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT  
+
+      - name: Show Result
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --details \
+            --region us-west-1 \
+            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,Output:CommandPlugins[0].Output}" \
+            --output table
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --details \
+            --region us-west-1 \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text)
+
+          echo "Failed Instances: $FAILED"
+
+          if [ "$FAILED" -gt 0 ]; then
+            echo "::error::$FAILED instance(s) failed database initialization."
+            exit 1
+          fi
+
+          echo "✅ Database initialized successfully on all instances."0904
