baby

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -3,7 +3,6 @@ name: Test Fleet health and Env Variables
 on:
   workflow_call:
 
-
 permissions:
   id-token: write
   contents: read
@@ -11,49 +10,57 @@ permissions:
 jobs:
   test:
     runs-on: ubuntu-latest
+
     steps:
+      - uses: actions/checkout@v4
+
       - uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::594474085977:role/github-action-deploy-role
+          role-to-assume: arn:aws:iam::594474085977:role/github_action_deploy_role
           aws-region: us-west-1
 
-      - name: Fleet health check
+      - name: Fleet Health Check
         id: health
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":["hostname -I"
-            "docker --version 2>/dev/null || echo Docker not installed",
-            "aws --version 22>/dev/null || echo AWS CLI not installed",
-            "mysql --version 2>/dev/null || echo MySQL not installed",
-            "aws ssm get-parameters-by-path /application/banking --with-decryption --region us-west-1"
-            ]}' \
-            --query 'Command.CommandId' --output text \
+            --parameters '{
+              "commands":[
+                "hostname -I",
+                "docker --version 2>/dev/null || echo Docker not installed",
+                "aws --version 2>/dev/null || echo AWS CLI not installed",
+                "mysql --version 2>/dev/null || echo MySQL not installed",
+                "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-west-1"
+              ]
+            }' \
+            --query "Command.CommandId" \
+            --output text \
             --region us-west-1)
-          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUTPUT
+
+          echo "CMD_ID=$CMD_ID" >> $GITHUB_ENV
 
       - name: Show Results
         run: |
           sleep 20
 
           aws ssm list-command-invocations \
-            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --command-id "$CMD_ID" \
+            --details \
             --region us-west-1 \
-            --query "CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[0].Output}" \
+            --query "CommandInvocations[*].{Instance:InstanceId,Output:CommandPlugins[0].Output}" \
             --output table
 
+          FAILED_INSTANCES=$(aws ssm list-command-invocations \
+            --command-id "$CMD_ID" \
+            --details \
+            --region us-west-1 \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text)
 
-          FAILED=$(aws ssm list-command-invocations \
-            --command-id "${{steps.health.outputs.cmd_id}}" --details \
-            --query "length(commandinvocations[?status=='Failed'])" \
-            --output text \
-            --region us-west-1
-            )
+          if [ "$FAILED_INSTANCES" -gt 0 ]; then
+            echo "::error::Health check failed on $FAILED_INSTANCES instance(s)"
+            exit 1
+          fi
 
-
-          [ "$FAILED_" -gt 0 ] && \
-           echo "::error::Health check Failed on $FAILED_ instance(s)" && \
-           exit 1 
-
-           echo "All Instances Healthy ✅"
+          echo "All instances are healthy ✅"
