devil code

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -1,7 +1,8 @@
-name: Test fleet health and env variable
+name: Test Fleet health and Env Variables
 
 on:
   workflow_call:
+
 
 permissions:
   id-token: write
@@ -10,55 +11,50 @@ permissions:
 jobs:
   test:
     runs-on: ubuntu-latest
-
     steps:
       - uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::594474085977:role/github-action-deploy-role
           aws-region: us-west-1
 
-      - name: Fleet heatlh check
+      - name: Fleet Health Checks
         id: health
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
             --parameters '{"commands":[
-            "hostname -I",
-            "docker --version 2>/dev/null || echo DOCKER NOT INSTALLED",
-            "aws --version 2>/dev/null || echo AWS NOT INSTALLED",
-            "mysql --version 2>/dev/null || echo MYSQL NOT INSTALLED",
-            "aws ssm get-parameters-by-path --path /application/testing --with-decryption --region us-west-1"
-            ]}' \
+              "hostname -I",
+              "docker --version 2>/dev/null  echo DOCKER NOT INSTALLED",
+              "aws --version 2>/dev/null  echo AWS CLI NOT INSTALLED",
+              "mysql --version 2>/dev/null || echo MYSQL NOT INSTALLED",
+              "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-west-1 | grep -E Name"
+              ]}' \
             --query 'Command.CommandId' \
             --output text \
-            --region us-west-1)
-
+            --region us-west-1
+            )
           echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
-
-      - name: Show Result
-        run: |
-          sleep 60
-
+      
+      
+      - name: Show Results
+        run: |  
+          sleep 20
           aws ssm list-command-invocations \
             --command-id "${{ steps.health.outputs.cmd_id }}" \
             --details \
-            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,IP:CommandPlugins[0].Output}" \
+            --region us-west-1 \
+            --output text 
+          
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
             --output text \
-            --region us-west-1 
-
-          FAILD=$(
-            aws ssm list-command-invocations \
-              --command-id "${{ steps.health.outputs.cmd_id }}" \
-              --details \
-              --query "length(CommandInvocations[?Status=='Failed'])" \
-              --output text \
-              --region us-west-1 
+            --region us-west-1
             )
 
-          [ "$FAILD" -gt 0 ] && \
-          echo "::error::Health Check Faild on $FAILD instance(s)" && \
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Health Check Failed on $FAILED instances" && \
           exit 1
 
-
-          echo "All Instance Healthy"
+          echo "ALL Instances Healthy ✅"
